// Generated by Copilot
import { Component, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-calendar',
  imports: [CommonModule],
  template: `
    <div class="dashboard-section calendar">
      <div class="dashboard-title">Kalendarz</div>
      <div class="dashboard-value">{{ date }}</div>
      <div class="calendar-year">
        <div class="calendar-row" *ngFor="let row of getCalendarRows(); let rowIdx = index">
          <div class="calendar-month" *ngFor="let cal of row; let monthIdx = index">
            <div class="calendar-month-title">{{ cal.month }}</div>
            <div class="calendar-grid">
              <div class="calendar-header" *ngFor="let day of weekDays">{{ day }}</div>
              <div class="calendar-cell empty" *ngFor="let _ of cal.padding"></div>
              <div 
                class="calendar-cell" 
                *ngFor="let day of cal.days; let dayIdx = index"
                [ngClass]="isToday(rowIdx * 4 + monthIdx, day) ? 'calendar-today' : ''"
              >
                {{ day }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: `
    .dashboard-section {
      background: #fff;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.07);
      padding: 1.5rem 2rem;
      min-width: 220px;
      text-align: center;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .dashboard-title {
      font-size: 1.1rem;
      font-weight: bold;
      margin-bottom: 0.5rem;
      color: #222;
    }
    .dashboard-value {
      font-size: 1.5rem;
      color: #0d4e8e;
      min-height: 2.5rem;
      margin-bottom: 1rem;
    }
    .calendar-year {
      display: flex;
      flex-direction: column;
      gap: 2rem;
      justify-content: center;
      margin-top: 1rem;
    }
    .calendar-row {
      display: flex;
      flex-wrap: nowrap;
      gap: 3.5rem; /* Increased horizontal gap between months */
      justify-content: center;
    }
    .calendar-month {
      min-width: 220px;
      margin-bottom: 2rem;
    }
    .calendar-month-title {
      font-weight: bold;
      color: #0d4e8e;
      margin-bottom: 0.3rem;
      text-align: center;
    }
    .calendar-grid {
      display: grid;
      grid-template-columns: repeat(7, 2.2rem);
      gap: 0.2rem;
      margin-top: 0.5rem;
    }
    .calendar-header {
      font-weight: bold;
      color: #555;
      font-size: 0.95rem;
      text-align: center;
    }
    .calendar-cell {
      background: #f5f5f5;
      border-radius: 4px;
      padding: 0.3rem 0;
      text-align: center;
      font-size: 1rem;
      color: #333;
    }
    .calendar-cell.empty {
      background: transparent;
      pointer-events: none;
    }
    .calendar-today {
      background: #0d4e8e !important;
      color: #fff !important;
      font-weight: bold;
      border: 2px solid #0d4e8e;
    }
  `,
})
export class Calendar implements OnDestroy {
  public monthsPL = [
    'Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec',
    'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'
  ];
  public weekDays = ['Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'Sb', 'Nd'];
  public yearCalendars: { month: string, days: number[], padding: undefined[] }[] = [];
  public date = '';
  private timerId: ReturnType<typeof setInterval> | undefined;

  public constructor() {
    this.updateTime();
    this.timerId = setInterval(() => this.updateTime(), 1000);
    this.generateYearCalendar();
  }

  public updateTime(): void {
    const now = new Date();
    this.date = now.toLocaleDateString('pl-PL', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    // Regenerate year calendar if year changes
    this.generateYearCalendar();
  }

  public generateYearCalendar(): void {
    const now = new Date();
    const year = now.getFullYear();
    this.yearCalendars = [];
    for (let month = 0; month < 12; month++) {
      const firstDay = new Date(year, month, 1);
      const lastDay = new Date(year, month + 1, 0);
      const daysInMonth = lastDay.getDate();
      let startDay = firstDay.getDay();
      startDay = (startDay === 0) ? 6 : startDay - 1;
      const padding = Array(startDay).fill(undefined);
      const days = Array.from({ length: daysInMonth }, (_, i) => i + 1);
      this.yearCalendars.push({ month: this.monthsPL[month] + ' ' + year, days, padding });
    }
  }

  public getCalendarRows(): { month: string, days: number[], padding: undefined[] }[][] {
    // Split yearCalendars into rows of 4 months each
    const rows = [];
    for (let i = 0; i < this.yearCalendars.length; i += 4) {
      rows.push(this.yearCalendars.slice(i, i + 4));
    }
    return rows;
  }

  public isToday(monthIndex: number, day: number): boolean {
    const today = new Date();
    return (
      today.getFullYear() === new Date().getFullYear() &&
      today.getMonth() === monthIndex &&
      today.getDate() === day
    );
  }

  public ngOnDestroy(): void {
    if (this.timerId) clearInterval(this.timerId);
  }
}
